name: PlayerBounty
main: com.dachiimp.playerbounty.Bounty
version: 1.0
description: >
             DaChiimps's PlayerBounty Plugin
commands:
    bounty:
        description: Set a bounty
    bounties:
        description: View player bounties
